### ISSUE TITLE
Array Index Out of Bound Exception

### ISSUE THREAD

**Issue by fireworkstech** [DavidPizarro/PickerUI#16]
`  java.lang.ArrayIndexOutOfBoundsException: length=10; index=10
                                                                                 at java.util.Arrays$ArrayList.get(Arrays.java:3854)
                                                                                 at com.dpizarro.uipicker.library.picker.PickerUIListView$4.run(PickerUIListView.java:218)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by kashlo** [comment]
same here

**Comment by alirezat66** [comment]
same error

**Comment by epictechnicaltricks** [comment]
I have done various changes but not work anything but when I have set height to 200dp my issue fixed, 

my xml code 


 <com.dpizarro.uipicker.library.picker.PickerUI
                android:translationY="-20dp"
                android:layout_height="200dp"
                android:layout_weight="1.4"
                android:scaleX="0.8"
                android:scaleY="0.8"
                android:id="@+id/picker_ui_view"
                android:layout_width="wrap_content"
                pickerui:backgroundColor="@color/transparent"
                pickerui:linesCenterColor="@color/black"
                pickerui:autoDismiss="false"
                android:layout_marginStart="10dp"
                pickerui:itemsClickables="true"
                pickerui:textCenterColor="#000000"
                pickerui:textNoCenterColor="#737373"
                app:blur="false"
                />
